DROP TABLE IF EXISTS audio_tracks;

CREATE TABLE audio_tracks (
    id INT IDENTITY(1,1) PRIMARY KEY,
    youtube_id NVARCHAR(255) NOT NULL,
    artist NVARCHAR(255) NOT NULL,
    track_name NVARCHAR(255) NOT NULL,
    track_audio NVARCHAR(MAX) NOT NULL,
    thumbnail NVARCHAR(MAX) NULL
);

-- TODO: CREATE TABLE FOR TRACK TIMESTAMPS WITH LOOPS AND OTHER FEATURES